Repository AY2324S2-CS2113-F15-4/tp, pull requests merged in 2024-04, with the labels that each got.

#57 Update set-genre function for a more user-friendly user experience
  src/main/java/seedu/bookbuddy/BookDetails.java
  src/main/java/seedu/bookbuddy/BookList.java
  src/main/java/seedu/bookbuddy/Parser.java
  src/test/java/seedu/bookbuddy/ParserTest.java
Labels: enhancement, priority.Medium, type.Story, type.Enhancement, severity.Medium

#58 Add rating system for books. Rate books and list books based on good …
  src/main/java/seedu/bookbuddy/Book.java
  src/main/java/seedu/bookbuddy/BookBuddy.java
  src/main/java/seedu/bookbuddy/BookDetails.java
  src/main/java/seedu/bookbuddy/BookList.java
  src/main/java/seedu/bookbuddy/Parser.java
  src/main/java/seedu/bookbuddy/Ui.java
Labels: priority.Medium, type.Story, severity.Medium

#61 Abstract BookDetails into concise accurate classes.
  src/main/java/seedu/bookbuddy/BookBuddy.java
  src/main/java/seedu/bookbuddy/BookDetails.java
  src/main/java/seedu/bookbuddy/BookList.java
  src/main/java/seedu/bookbuddy/Parser.java
  src/main/java/seedu/bookbuddy/bookdetails/BookDisplay.java
  src/main/java/seedu/bookbuddy/bookdetails/BookGenre.java
  src/main/java/seedu/bookbuddy/bookdetails/BookLabel.java
  src/main/java/seedu/bookbuddy/bookdetails/BookRating.java
  src/main/java/seedu/bookbuddy/bookdetails/BookSummary.java
  src/test/java/seedu/bookbuddy/BookDetailsTest.java
  src/test/java/seedu/bookbuddy/ParserTest.java
Labels: priority.Medium, type.Bug, severity.Medium

#72 Branch zongyao abstraction
  src/main/java/seedu/bookbuddy/Book.java
  src/main/java/seedu/bookbuddy/BookBuddy.java
  src/main/java/seedu/bookbuddy/BookList.java
  src/main/java/seedu/bookbuddy/FileStorage.java
  src/main/java/seedu/bookbuddy/Parser.java
  src/main/java/seedu/bookbuddy/Ui.java
  src/main/java/seedu/bookbuddy/book/BookMain.java
  src/main/java/seedu/bookbuddy/book/Genre.java
  src/main/java/seedu/bookbuddy/book/Label.java
  src/main/java/seedu/bookbuddy/book/Rating.java
  src/main/java/seedu/bookbuddy/book/Read.java
  src/main/java/seedu/bookbuddy/book/Summary.java
  src/main/java/seedu/bookbuddy/book/Title.java
  src/main/java/seedu/bookbuddy/bookdetails/BookDisplay.java
  src/main/java/seedu/bookbuddy/bookdetailsmodifier/BookDisplay.java
  src/main/java/seedu/bookbuddy/bookdetailsmodifier/BookGenre.java
  src/main/java/seedu/bookbuddy/bookdetailsmodifier/BookLabel.java
  src/main/java/seedu/bookbuddy/bookdetailsmodifier/BookMark.java
  src/main/java/seedu/bookbuddy/bookdetailsmodifier/BookRating.java
  src/main/java/seedu/bookbuddy/bookdetailsmodifier/BookSummary.java
  src/main/java/seedu/bookbuddy/booklist/BookList.java
  src/main/java/seedu/bookbuddy/booklist/BookListModifier.java
  src/main/java/seedu/bookbuddy/parser/ParserMain.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/ParserAdd.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/ParserDisplay.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/ParserGenre.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/ParserLabel.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/ParserMark.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/ParserRating.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/ParserRemove.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/ParserSummary.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/ParserUnmark.java
  src/main/java/seedu/bookbuddy/parser/parservalidation/CommandList.java
  src/main/java/seedu/bookbuddy/parser/parservalidation/Exceptions.java
  src/test/java/seedu/bookbuddy/BookDetailsTest.java
  src/test/java/seedu/bookbuddy/BookListTest.java
  src/test/java/seedu/bookbuddy/ParserMainTest.java
Labels: priority.Medium, type.Task, type.Bug, severity.Medium

#75 Find function
  BookBuddy.log.1
  src/main/java/seedu/bookbuddy/Ui.java
  src/main/java/seedu/bookbuddy/bookdetailsmodifier/BookDisplay.java
  src/main/java/seedu/bookbuddy/parser/ParserMain.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/ParserFind.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/ParserGenre.java
  src/main/java/seedu/bookbuddy/parser/parservalidation/CommandList.java
Labels: priority.Medium, type.Story

#77 Authorship edits
  src/main/java/seedu/bookbuddy/book/BookMain.java
Labels: priority.Medium

#84 Update User Guide to show target users and value proposition
  docs/UserGuide.md
Labels: documentation, priority.Medium, type.Task

#85 Expanding find function and update user guide
  docs/UserGuide.md
  src/main/java/seedu/bookbuddy/Ui.java
  src/main/java/seedu/bookbuddy/bookdetailsmodifier/BookDisplay.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/ParserFind.java
Labels: documentation

#86 find based on read and unread status implemented
  src/main/java/seedu/bookbuddy/bookdetailsmodifier/BookDisplay.java
  src/main/java/seedu/bookbuddy/parser/ParserMain.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/ParserFind.java
  src/main/java/seedu/bookbuddy/parser/parservalidation/CommandList.java
Labels: priority.Medium, type.Enhancement

#87 updated UG and list of commands in help
  docs/UserGuide.md
  src/main/java/seedu/bookbuddy/Ui.java
Labels: documentation, enhancement

#88 Add single step operation of set-genre method for pro users
  src/main/java/seedu/bookbuddy/Ui.java
  src/main/java/seedu/bookbuddy/parser/ParserMain.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/ParserGenre.java
  src/test/java/seedu/bookbuddy/ParserMainTest.java
Labels: bug, priority.Medium, type.Enhancement, type.Task, type.Bug, severity.Medium

#89 Update user guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation, type.Task

#94 fix bug such that capitalization of letters do not matter when using …
  BookBuddy.log.1
  src/main/java/seedu/bookbuddy/bookdetailsmodifier/BookDisplay.java
  src/main/java/seedu/bookbuddy/parser/ParserMain.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/ParserFind.java
Labels: bug, enhancement, priority.Medium

#96 Bug fix for set-genre feature
  src/main/java/seedu/bookbuddy/parser/parsercommands/ParserGenre.java
  src/test/java/seedu/bookbuddy/ParserMainTest.java
Labels: bug, priority.High, type.Bug

#97 Fix bugs in genre and label commands
  src/main/java/seedu/bookbuddy/parser/parsercommands/ParserGenre.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/ParserLabel.java
Labels: bug, type.Bug, severity.Medium

#102 update find-label feature
  src/main/java/seedu/bookbuddy/bookdetailsmodifier/BookDisplay.java
Labels: priority.Medium

#149 modifications
  src/main/java/seedu/bookbuddy/Ui.java
  src/main/java/seedu/bookbuddy/bookdetailsmodifier/BookDisplay.java
  src/main/java/seedu/bookbuddy/bookdetailsmodifier/BookFind.java
  src/main/java/seedu/bookbuddy/bookdetailsmodifier/BookMark.java
  src/test/java/seedu/bookbuddy/BookListTest.java
Labels: enhancement

#150 fix find-genre issue
  src/main/java/seedu/bookbuddy/bookdetailsmodifier/BookFind.java
Labels: priority.High

#151 find-rate function added
  src/main/java/seedu/bookbuddy/Ui.java
  src/main/java/seedu/bookbuddy/bookdetailsmodifier/BookFind.java
  src/main/java/seedu/bookbuddy/parser/ParserMain.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/ParserFind.java
  src/main/java/seedu/bookbuddy/parser/parservalidation/CommandList.java
Labels: enhancement, priority.Medium

#152 update UG
  docs/UserGuide.md
  src/main/java/seedu/bookbuddy/Ui.java
Labels: documentation

#153 Add list-by-date command
  src/main/java/seedu/bookbuddy/bookdetailsmodifier/BookMark.java
  src/main/java/seedu/bookbuddy/parser/ParserMain.java
  src/main/java/seedu/bookbuddy/parser/parservalidation/CommandList.java
  src/main/java/utils/DateTimeUtils.java
Labels: enhancement

#154 Update UG and add javadocs
  docs/UserGuide.md
  src/main/java/seedu/bookbuddy/Ui.java
  src/main/java/utils/DateTimeUtils.java
Labels: documentation

#156 Bug fixes -
  src/main/java/exceptions/InvalidInputException.java
  src/main/java/seedu/bookbuddy/BookBuddy.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/ParserFind.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/ParserGenre.java
  src/main/java/seedu/bookbuddy/parser/parservalidation/Exceptions.java
Labels: bug, enhancement, priority.Medium, type.Enhancement, type.Task, type.Bug, severity.Medium

#158 Branch zongyao pedbugs
  src/main/java/seedu/bookbuddy/bookdetailsmodifier/BookLabel.java
  src/main/java/seedu/bookbuddy/booklist/BookList.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/ParserGenre.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/ParserLabel.java
Labels: bug, enhancement, priority.Medium, type.Bug, severity.Medium

#159 Bug fixes -
  docs/UserGuide.md
  src/main/java/seedu/bookbuddy/FileStorage.java
  src/main/java/seedu/bookbuddy/booklist/BookList.java
Labels: bug, enhancement, priority.Medium, type.Enhancement, type.Bug, severity.Medium

#160 Branch zongyao pedbugs
  docs/UML_Files/SetGenreSequenceDiagram.puml
Labels: bug, documentation, priority.Medium, type.Bug, severity.Medium

#161 Update Developer Guide to include sequence diagrams for set-label fea…
  docs/DeveloperGuide.md
  docs/UML_Files/SetLabelSequenceDiagram.puml
  docs/UML_diagrams/SetGenreSequenceDiagram.png
  docs/UML_diagrams/SetLabelSequenceDiagram.png
Labels: documentation, priority.Medium

#164 Bug fix - immutable list cannot be modified. Changed it to be modifiable
  src/main/java/seedu/bookbuddy/booklist/BookList.java
Labels: bug, priority.High, type.Bug, severity.High

#165 Bug Fix PED: Mishandling for incorrect user commands for METHOD: list
  src/main/java/seedu/bookbuddy/bookdetailsmodifier/BookMark.java
  src/main/java/seedu/bookbuddy/parser/ParserMain.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/ParserList.java
  src/main/java/seedu/bookbuddy/parser/parservalidation/Exceptions.java
Labels: type.Bug, severity.VeryLow

#168 Branch author
  src/main/java/seedu/bookbuddy/Ui.java
  src/main/java/seedu/bookbuddy/book/Author.java
  src/main/java/seedu/bookbuddy/book/BookMain.java
  src/main/java/seedu/bookbuddy/bookdetailsmodifier/BookAuthor.java
  src/main/java/seedu/bookbuddy/bookdetailsmodifier/BookDisplay.java
  src/main/java/seedu/bookbuddy/booklist/BookListModifier.java
  src/main/java/seedu/bookbuddy/parser/ParserMain.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/ParserAdd.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/ParserAuthor.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/ParserSummary.java
  src/main/java/seedu/bookbuddy/parser/parservalidation/CommandList.java
Labels: enhancement, priority.Medium

#169 Add check for duplicate books for add and set-author commands
  BookBuddy.log.1
  src/main/java/seedu/bookbuddy/Ui.java
  src/main/java/seedu/bookbuddy/booklist/BookList.java
  src/main/java/seedu/bookbuddy/booklist/BookListModifier.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/ParserAuthor.java
  src/test/java/seedu/bookbuddy/ParserMainTest.java
Labels: enhancement, severity.Medium

#171 Update UG and help command
  docs/UserGuide.md
  src/main/java/seedu/bookbuddy/Ui.java
Labels: documentation

#174 PPP update
  BookBuddy.log.1
  docs/team/johndoe.md
  docs/team/lordgareth10.md
Labels: documentation, type.Task

#175 Bug Fixes
  src/main/java/seedu/bookbuddy/parser/ParserMain.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/ParserAuthor.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/ParserFind.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/ParserGenre.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/ParserMark.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/ParserRemove.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/ParserSummary.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/ParserUnmark.java
Labels: bug, severity.Low

#179 Clean up code for set-genre, label and rate features and minor code e…
  src/main/java/seedu/bookbuddy/bookdetailsmodifier/BookDisplay.java
  src/main/java/seedu/bookbuddy/bookdetailsmodifier/BookRating.java
  src/main/java/seedu/bookbuddy/booklist/BookListModifier.java
  src/main/java/seedu/bookbuddy/parser/ParserMain.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/ParserAdd.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/ParserFind.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/ParserGenre.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/ParserList.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/ParserRemove.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/parsegenre/InputLooper.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/parsegenre/NewGenreModifier.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/parsegenre/ParserGenre.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/parserating/ParserRating.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/parserating/RatingChecks.java
Labels: enhancement, priority.Medium, severity.Low

#180 Added Junit tests for SetBookRating, ParserRating, ParseList, ParseLi…
  src/main/java/seedu/bookbuddy/booklist/BookList.java
  src/test/java/seedu/bookbuddy/BookDetailsTest.java
  src/test/java/seedu/bookbuddy/ParserMainTest.java
Labels: priority.Medium, type.Enhancement

#182 Bug fix - change availablegenre arraylist to be non-static. Reformatt…
  src/main/java/seedu/bookbuddy/FileStorage.java
  src/main/java/seedu/bookbuddy/booklist/BookList.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/ParserFind.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/parsegenre/InputLooper.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/parsegenre/NewGenreModifier.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/parsegenre/ParserGenre.java
  src/test/java/seedu/bookbuddy/ParserMainTest.java
Labels: bug, priority.Medium, type.Bug, severity.Medium

#189 Fixed bug where user is unable to exit from secondary input to primary input in set-genre function
  src/main/java/seedu/bookbuddy/Ui.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/parsegenre/InputLooper.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/parsegenre/NewGenreModifier.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/parsegenre/ParserGenre.java
Labels: bug, priority.Medium, severity.Medium

#190 Fix bug where user will not get warning if giving same rating or label to a book when they have already given the same one before
  src/main/java/seedu/bookbuddy/Ui.java
  src/main/java/seedu/bookbuddy/bookdetailsmodifier/BookLabel.java
  src/main/java/seedu/bookbuddy/bookdetailsmodifier/BookRating.java
Labels: bug, priority.Medium, type.Bug, severity.Low

#191 Added features to remove genre and to list the current available genres
  src/main/java/seedu/bookbuddy/FileStorage.java
  src/main/java/seedu/bookbuddy/Ui.java
  src/main/java/seedu/bookbuddy/booklist/BookList.java
  src/main/java/seedu/bookbuddy/booklist/GenreList.java
  src/main/java/seedu/bookbuddy/parser/ParserMain.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/ParserFind.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/ParserList.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/ParserRemoveGenre.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/parsegenre/InputLooper.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/parsegenre/NewGenreModifier.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/parserating/RatingChecks.java
  src/main/java/seedu/bookbuddy/parser/parservalidation/CommandList.java
  src/test/java/seedu/bookbuddy/ParserMainTest.java
Labels: bug, enhancement, priority.Medium, type.Bug, severity.Medium

#192 Add Junit test cases for features by zong yao
  src/main/java/seedu/bookbuddy/parser/parsercommands/parsegenre/InputLooper.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/parsegenre/ParserGenre.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/parserating/RatingChecks.java
  src/test/java/seedu/bookbuddy/parser/parsercommands/ParserAddTest.java
  src/test/java/seedu/bookbuddy/parser/parsercommands/ParserLabelTest.java
  src/test/java/seedu/bookbuddy/parser/parsercommands/ParserListTest.java
  src/test/java/seedu/bookbuddy/parser/parsercommands/ParserRemoveGenreTest.java
  src/test/java/seedu/bookbuddy/parser/parsercommands/parsegenre/InputLooperTest.java
  src/test/java/seedu/bookbuddy/parser/parsercommands/parsegenre/NewGenreModifierTest.java
  src/test/java/seedu/bookbuddy/parser/parsercommands/parsegenre/ParserGenreTest.java
  src/test/java/seedu/bookbuddy/parser/parsercommands/parserating/ParserRatingTest.java
  src/test/java/seedu/bookbuddy/parser/parsercommands/parserating/RatingChecksTest.java
Labels: enhancement, priority.Medium, severity.Medium

#195 Added documentation and minor bug fixes
  src/main/java/seedu/bookbuddy/book/Genre.java
  src/main/java/seedu/bookbuddy/book/Label.java
  src/main/java/seedu/bookbuddy/book/Rating.java
  src/main/java/seedu/bookbuddy/bookdetailsmodifier/BookGenre.java
  src/main/java/seedu/bookbuddy/bookdetailsmodifier/BookLabel.java
  src/main/java/seedu/bookbuddy/bookdetailsmodifier/BookRating.java
  src/main/java/seedu/bookbuddy/booklist/GenreList.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/ParserAdd.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/ParserLabel.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/ParserRemoveGenre.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/parsegenre/InputLooper.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/parsegenre/NewGenreModifier.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/parsegenre/ParserGenre.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/parserating/ParserRating.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/parserating/RatingChecks.java
Labels: documentation, priority.Medium, severity.Low, severity.Medium

#196 Added documentation in developer guide - Set Rating feature and BookM…
  docs/DeveloperGuide.md
  docs/UML_Files/BookMainClassDiagram.puml
  docs/UML_Files/SetRatingSequenceDiagram.puml
  docs/UML_diagrams/BookMainClassDiagram.png
  docs/UML_diagrams/SetRatingSequenceDiagram.png
  docs/UserGuide.md
Labels: documentation, enhancement, priority.Medium, severity.Low

#197 Bug fix - set-genre feature loop does not continue when a wrong input…
  src/main/java/seedu/bookbuddy/parser/parsercommands/parsegenre/InputLooper.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/parsegenre/ParserGenre.java
  src/main/java/seedu/bookbuddy/parser/parservalidation/Exceptions.java
Labels: bug, priority.High, type.Bug, severity.High

#204 Bug fix - accurate exception messages
  src/main/java/seedu/bookbuddy/parser/parsercommands/parsegenre/InputLooper.java
Labels: bug, priority.Medium, type.Bug, severity.Medium

#205 Add UML diagrams and more JUnit tests
  docs/AboutUs.md
  docs/UML_Files/ListCommand.puml
  docs/UML_Files/MarkCommand.puml
  docs/UML_Files/SetAuthorSequenceDaigram.puml
  docs/UML_diagrams/ListCommand.png
  docs/UML_diagrams/MarkCommand.png
  docs/UML_diagrams/SetAuthorSequenceDaigram.png
  docs/team/lordgareth10.md
  src/test/java/seedu/bookbuddy/BookDetailsTest.java
  src/test/java/seedu/bookbuddy/BookListTest.java
  src/test/java/seedu/bookbuddy/ParserMainTest.java
Labels: documentation

#209 Bug fix - rate 0 1 and label 0 1 will give a wrong error message
  src/main/java/seedu/bookbuddy/Ui.java
  src/main/java/seedu/bookbuddy/bookdetailsmodifier/BookRating.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/ParserLabel.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/parsegenre/InputLooper.java
  src/test/java/seedu/bookbuddy/parser/parsercommands/ParserLabelTest.java
Labels: bug, priority.High, type.Bug, severity.Medium

#213 Branch zongyao codeenhancements
  README.md
  docs/AboutUs.md
  docs/team/yeozongyao.md
Labels: documentation, priority.Medium

#214 Bug Fixes: Corrected error messages
  docs/team/lordgareth10.md
  src/main/java/seedu/bookbuddy/Ui.java
  src/main/java/seedu/bookbuddy/bookdetailsmodifier/BookFind.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/ParserRemoveGenre.java
Labels: documentation, type.Bug, severity.VeryLow

#218 Bug fix - replace split criteria as \\s+ instead of space
  src/main/java/seedu/bookbuddy/parser/ParserMain.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/ParserAuthor.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/ParserLabel.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/ParserSummary.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/parsegenre/ParserGenre.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/parserating/RatingChecks.java
Labels: bug, priority.Medium, type.Bug, severity.Medium

#221 Refactor code for set-genre feature for code readability
  src/main/java/seedu/bookbuddy/parser/parsercommands/parsegenre/GenreChecker.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/parsegenre/InputHandler.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/parsegenre/InputLooper.java
Labels: priority.Medium, type.Task

#223 Bug Fixes and refactoring
  docs/DeveloperGuide.md
  src/main/java/seedu/bookbuddy/Ui.java
  src/main/java/seedu/bookbuddy/bookdetailsmodifier/BookMark.java
  src/main/java/seedu/bookbuddy/booklist/BookListModifier.java
  src/main/java/seedu/bookbuddy/parser/ParserMain.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/ParserFind.java
  src/main/java/seedu/bookbuddy/parser/parsercommands/ParserHelp.java
Labels: bug, documentation

#227 Update user guide
  docs/UserGuide.md
Labels: bug, documentation, priority.Medium
