Repository AY2324S2-CS2113-F15-4/tp, pull requests merged in 2024-03, with the labels that each got.

#14 Merge master
  src/main/java/seedu/bookbuddy/Book.java
  src/main/java/seedu/bookbuddy/BookBuddy.java
  src/main/java/seedu/bookbuddy/BookList.java
  src/main/java/seedu/bookbuddy/Parser.java
  src/test/java/seedu/bookbuddy/BookListTest.java
  src/test/java/seedu/bookbuddy/ParserTest.java
  text-ui-test/EXPECTED.TXT
Labels: documentation, priority.High, type.Story

#20 Defensive Coding - Adding assertions and logging
  build.gradle
  src/main/java/seedu/bookbuddy/BookBuddy.java
  src/main/java/seedu/bookbuddy/BookList.java
  src/main/java/seedu/bookbuddy/Parser.java
Labels: priority.Medium

#25 Coding standard fixes
  src/main/java/exceptions/BookNotFoundException.java
  src/main/java/exceptions/InvalidBookIndexException.java
  src/main/java/seedu/bookbuddy/BookBuddy.java
Labels: priority.Medium, type.Bug

#28 Assertions in BookList class
  src/main/java/seedu/bookbuddy/BookList.java
  src/main/java/seedu/bookbuddy/Parser.java
Labels: priority.High, type.Task

#33 Branch defensive coding
  src/main/java/exceptions/BookBuddyException.java
  src/main/java/exceptions/InvalidBookIndexException.java
  src/main/java/seedu/bookbuddy/BookBuddy.java
  src/main/java/seedu/bookbuddy/BookList.java
  src/main/java/seedu/bookbuddy/Parser.java
  src/test/java/seedu/bookbuddy/ParserTest.java
Labels: bug

#34 Assertions
  BookBuddy.log
  src/main/java/seedu/bookbuddy/BookList.java
Labels: priority.Medium

#37 Branch zongyao defensive coding
  build.gradle
  src/main/java/seedu/bookbuddy/BookBuddy.java
  src/main/java/seedu/bookbuddy/BookList.java
  src/main/java/seedu/bookbuddy/Parser.java
  src/test/java/seedu/bookbuddy/BookListTest.java
  src/test/java/seedu/bookbuddy/ParserTest.java
Labels: priority.Medium, type.Task

#41 Categorise the books with personalised labels and with the genre
  src/main/java/seedu/bookbuddy/Book.java
  src/main/java/seedu/bookbuddy/BookDetails.java
  src/main/java/seedu/bookbuddy/Parser.java
  src/main/java/seedu/bookbuddy/Ui.java
Labels: priority.High

#51 Huge bug fix related to static inheritance
  src/main/java/seedu/bookbuddy/BookDetails.java
  src/main/java/seedu/bookbuddy/BookList.java
  src/main/java/seedu/bookbuddy/Parser.java
  src/main/java/seedu/bookbuddy/Ui.java
  src/test/java/seedu/bookbuddy/ParserTest.java
Labels: bug, priority.High, type.Bug, severity.High

#52 Added Junit test cases for set label and set genre
  src/test/java/seedu/bookbuddy/BookDetailsTest.java
  src/test/java/seedu/bookbuddy/ParserTest.java
Labels: priority.Medium, type.Task
